In [51]:
from google.colab import files
uploaded = files.upload()

Saving quikr_car.csv to quikr_car (3).csv

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [53]:
df=pd.read_csv("quikr_car.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [30]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [ ]:
df.shape

(892, 6)

In [54]:
df['kms_driven']=df['kms_driven'].str.replace('kms','')
df['kms_driven']=df['kms_driven'].str.replace(',','')
df['kms_driven']=df['kms_driven'].str.replace('Petrol','')
df['kms_driven']=pd.to_numeric(df['kms_driven'],errors='coerce')

In [55]:
df['kms_driven']=df['kms_driven'].fillna(method='ffill').fillna(method='bfill')

In [56]:

df['fuel_type']=df['fuel_type'].fillna(method='ffill').fillna(method='bfill')

In [57]:
df['Price']=df['Price'].str.replace(',','')
df['Price']=df['Price'].str.replace('Ask For Price','')
df['Price']=pd.to_numeric(df['Price'],errors='coerce')

In [58]:
df.isnull().sum()

name           0
company        0
year           0
Price         35
kms_driven     0
fuel_type      0
dtype: int64

In [59]:
df['Price']=df['Price'].fillna(df['Price'].median())

In [60]:
df.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    float64
 4   kms_driven  892 non-null    float64
 5   fuel_type   892 non-null    object
dtypes: float64(2), object(4)
memory usage: 41.9+ KB

In [62]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [63]:
df['year']=pd.to_numeric(df['year'],errors='coerce')

In [64]:
df.isnull().sum()

name           0
company        0
year          50
Price          0
kms_driven     0
fuel_type      0
dtype: int64

In [65]:
df['year']=df['year'].fillna(method='ffill').fillna(method='bfill')

In [66]:
df['Price']=df['Price'].astype(int)
df['kms_driven']=df['kms_driven'].astype(int)
df['year']=df['year'].astype(int)

In [68]:
df.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    int64
 3   Price       892 non-null    int64
 4   kms_driven  892 non-null    int64
 5   fuel_type   892 non-null    object
dtypes: int64(3), object(3)
memory usage: 41.9+ KB

In [69]:
df.head(5)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,299999,22000,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel

In [70]:
df.describe()

              year         Price     kms_driven
count   892.000000  8.920000e+02     892.000000
mean   2012.536996  4.005808e+05   46514.589686
std       3.966722  4.567544e+05   34459.263394
min    1995.000000  3.000000e+04       0.000000
25%    2010.750000  1.787500e+05   25000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.750000e+05   58139.750000
max    2019.000000  8.500003e+06  400000.000000

In [74]:
df.to_csv("cleaned_car_data.csv", index=False)
files.download("cleaned_car_data.csv")